sonar.projectKey=codeexec
sonar.projectName=CodeExec
sonar.sources=backend/src,frontend/src
sonar.tests=backend/tests,frontend/src/__tests__
sonar.test.inclusions=**/*.test.js,**/*.test.jsx
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/prisma/**
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
sonar.host.url=http://sonarqube:9000
