---
- name: Deploy CodeExec on EC2
  hosts: codeexec
  become: true

  tasks:
    - name: Pull latest code
      git:
        repo: https://github.com/nikhil8995/CodeExec.git
        dest: /home/ubuntu/CodeExec
        version: main
        force: yes

    - name: Stop old containers
      command: docker rm -f codeexec-postgres codeexec-backend codeexec-frontend
      ignore_errors: true

    - name: Create network
      command: docker network create codeexec-network
      ignore_errors: true

    - name: Create volume
      command: docker volume create postgres_data
      ignore_errors: true

    - name: Run PostgreSQL
      command: >
        docker run -d --name codeexec-postgres
        --network codeexec-network
        -e POSTGRES_USER=postgres
        -e POSTGRES_PASSWORD=postgres
        -e POSTGRES_DB=codeexec
        -v postgres_data:/var/lib/postgresql/data
        -p 5432:5432 postgres:15

    - name: Wait for DB
      pause:
        seconds: 10

    - name: Build backend
      command: docker build -t codeexec-backend /home/ubuntu/CodeExec/backend

    - name: Run backend
      command: >
        docker run -d --name codeexec-backend
        --network codeexec-network
        -p 4000:4000
        -e DATABASE_URL=postgresql://postgres:postgres@codeexec-postgres:5432/codeexec
        -e JWT_SECRET=supersecret
        codeexec-backend

    - name: Run migrations
      command: docker exec codeexec-backend npx prisma migrate deploy
      ignore_errors: true

    - name: Build frontend
      command: >
        docker build --no-cache
        --build-arg VITE_API_URL=http://13.127.133.216:4000/api
        -t codeexec-frontend /home/ubuntu/CodeExec/frontend

    - name: Run frontend
      command: >
        docker run -d --name codeexec-frontend
        --network codeexec-network
        -p 5173:5173
        codeexec-frontend
